version: '3.8'

services:
  talkboard:
    build:
      context: ./
      args:
        STORAGE_TYPE: ${STORAGE_TYPE:-postgres}
    command: ./wait-for-postgres.sh db ./talkBoard
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - STORAGE_TYPE=${STORAGE_TYPE:-postgres}

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
